# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a567ec6be66fc8333dfdeb5478dc1e446dae6d9fa215f0da7b3c1cf9a87ffd20c06d02ea41d6028fbe456503b2b2089075116a167b1813ac0059d1328e2c95f0

test:
  secret_key_base: 955f395590d5584592d874a4c5d5acd452adc539dac3d0bf70624d9edc414748812aa85ececc103567808b155190f81f3811e1d298b4c6abe2c350b76635e55a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
